### ISSUE TITLE
plantuml integration

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/python-genpackagedoc#41]
genpackagedoc shall support plantuml.

For this integrated plantuml codes shall be rendered at build time.

**Comment by HolQue** [comment]
To make the same available in VS Codium directly, I suggest to let the Robot Framework AIO installer install the PlantUML extension for VS Codium also.

**Comment by test-fullautomation** [comment]
Hi Holger,
I  already created https://github.com/test-fullautomation/RobotFramework_AIO/issues/80 for tihs.
Thank you,
 Thomas

**Comment by HolQue** [comment]
Another aspect: `GenPackageDoc` is a standalone package (available outside the RobotFramework AIO also).

Therefore it is maybe not a good idea to let `GenpackageDoc` use PlantUML as extension for VS Codium - because in this case we have a dependency to VS Codium. This makes no sense.

Therefore a standalone installation of PlantUML is required also!

(Similar to Pandoc and LaTeX).

=> Task for the build process.

**Comment by test-fullautomation** [comment]
Hi Holger,

yes, of course.

genpackagedoc uses a VSCodium independent PlantUML.

VSCodium plugin is used for comfortable use.

Thank you,
 Thomas

**Comment by HolQue** [comment]
The GenPackageDoc configuration will have the following extension:

```
   "JAVA" : {
             "WINDOWS" : "%JAVA_HOME%/bin/java.exe",
             "LINUX"   : "${JAVA_HOME%}/bin/java"
            },

   "PLANT_UML" : {
                  "WINDOWS" : "%GENDOC_PLANTUML_PATH%/plantuml.jar",
                  "LINUX"   : "${GENDOC_PLANTUML_PATH}/plantuml"
                 }
```

The build process for Robot Framework AIO should make sure that `JAVA_HOME` and `GENDOC_PLANTUML_PATH` exist and have proper values.

This way of configuring PlantUML would also enable to use the `plantuml.jar` version from VS Codium plugin and we would not need to have a stand alone installation of PlantUML also.

**Comment by HolQue** [comment]
Trial version:

https://github.com/test-fullautomation/python-genpackagedoc/tree/HolQue/feat-41/plantuml_support

* downward compatible (PlantUML support is handled as option completely)
* fully implemented
* open only: documentation (but example available already)

**Comment by test-fullautomation** [comment]
Hi Holger,
please inform when tested.
Parts should be all integrated with latest version.
Thank you,
 Thomas

**Comment by HolQue** [comment]
Restest with latest Windows:build job:

Issue:

The value of

`GENDOC_PLANTUML_PATH=D:\RobotFramework\robotvscode\data\extensions\jebbs.plantuml-2.17.5-universal`

does not fit to the installation path:

`D:\RobotFramework\robotvscode\data\extensions\jebbs.plantuml-2.17.5`

**Comment by HolQue** [comment]
I corrected the path locally on my computer.

PlantUML is working now properly with GenPackageDoc.

**Comment by test-fullautomation** [comment]
Hi Ngoan,
can you please check why the provided path ends with "-universal"?
Please check also Linux. I did not find code for Linux-support in my pull-request review. Maybe I overlooked it?
Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi all,

initially I installed PlantUML in VSCodium manually. And I checked where to find the installation. And I found the required jar file within a path ending with "-universal". That's the reason.

BUT: The installer is not under our control. Also it can be seen, that the installation path contains a version number.

Consequence: The value of the environment variable is very dynamic and may change after every installation.

Therefore it would be helpful to let the build process check the current path after installation to detect if the path is still valid.

**Comment by test-fullautomation** [comment]
Hi Holger,
You need to take care that you start the VSCodium provided by our installer.
Important is that all VSCodium remains are removed from your machine.

RobotFramework AIO VSCodium comes with a specific PlantUML and VSCodium version which we select in our build process.
So the paths can be set properly.
@ngoan1608 : Please verify.

Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi Thomas,

yes, I do. I start: `%GENDOC_PLANTUML_PATH%/plantuml.jar`

And like I mentioned: For every installation the build process needs to take care of a valid value of this env var.

**Comment by ngoan1608** [comment]
Hi Thomas,

Please refer my below verifications:

> Hi Ngoan, can you please check why the provided path ends with "-universal"?

=> I have checked and observed that:
- When we install `PlantUML` extension manually from **Extension Marketplace** of **VsCodium**, the path to extension folder will ends with _"-universal"_.
- But when installing with our build process (download `*.vsix` file from https://open-vsx.org then install to VsCodium), the path to this extension will not contains _"-universal"_.

> Please check also Linux. I did not find code for Linux-support in my pull-request review. Maybe I overlooked it?

=> Yes, the implementation for Linux is missing now.

> RobotFramework AIO VSCodium comes with a specific PlantUML and VSCodium version which we select in our build process. So the paths can be set properly. @ngoan1608 : Please verify.

=> Yes, we now specify the version of VsCodium extension for installation ([vscode_requirement.csv](https://github.com/test-fullautomation/RobotFramework_AIO/blob/develop/install/vscode_requirement.csv)), so that the path to extension is under controlled.

----------
But I have some concerns when looking into this issue and https://github.com/test-fullautomation/RobotFramework_AIO/issues/80 issue:
- env var `GENDOC_PLANTUML_PATH` is only required for build process (likes `GENDOC_LATEXPATH` ) , is it right?
  => If yes, the environment setting on user machine when installation is not required (It is implemented for Windows as following https://github.com/test-fullautomation/RobotFramework_AIO/blob/e743c7f1006a65fc5639a25dd254afde94e29b4e/scripts/RobotFrameworkSetup.iss#L173)
- Shall we document or mention about env vars `GENDOC_PLANTUML_PATH` and `GENDOC_LATEXPATH` under this repo (sorry in case I missed the document but I cannot find information about these env vars in this repo), because they are required fof `genpackagedoc` to work properly.

Thank you,
Ngoan

**Comment by HolQue** [comment]
Hi Ngoan,

like the name of the environment variables indicate (starting with `GENDOC_` ...): they belong to the documentation tool chain (GenPackageDoc), and not to the build process immediately. The documentation is rendered when setup.py is executed. Therefore every developer need to have these variables established on his computer.

The environment variables required for GenPackageDoc, are explained in:
https://github.com/test-fullautomation/python-genpackagedoc/blob/develop/packagedoc/packagedoc_config.json

**Comment by test-fullautomation** [comment]
Hi Ngoan,
you are right. It's only required for a developer for our components to be able to build documentation. A RobotFramework AIO user does not need it.
But for component developers it need to be described that plantuml/GENDOC_PLANTUML_PATH are required.
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Proposals when discussing with @HolQue :
- `GENDOC_PLANTUML_PATH` is provided by separated patch, not by AIO installer
- `GENDOC_PLANTUML_PATH` and `GENDOC_LATEXPATH` need to mentioned in README file 
- The implementation for Linux is required (@ngoan1608 will do it in next PR)

**Comment by test-fullautomation** [comment]
Hi Ngoan,
I discussed the same again with Holger.
We identified the following requirement:
- build process need to use plantuml of vscodium for genpackagedoc execution.
  Therefore vscodium has to be aggregated before python (with setup.py of repositories) will be aggregated.
  After vscodium aggregation build process has to set the GENDOC_PLANTUML_PATH properly.
- Installers (Windows, Linux, OSS) need to set GENDOC_PLANTUML_PATH, too. This is required that after installation SeffTest can be executed. genpackagedoc selftest required plantuml to pass.

additional consequences 
- the first bullet point from your message is not correct.
- build order has to be changed.

Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi Thomas,

I [have updated the build pipeline](https://github.com/test-fullautomation/RobotFramework_AIO/commit/1042b4eae77c0cadeea2983af29c1fbb3a1c3da4#diff-d65208ea836263cde1581164810414e42328083ca358c2d6d6b0094993b0695b) and executed the pipeline before seeing your latest comments (GENDOC_PLANTUML_PATH is only set for build and selftest), the result is as below workflow:
https://github.com/test-fullautomation/RobotFramework_AIO/actions/runs/5066026691

It works fine excepts the error when executing genpackagedoc test on Linux as below log:
https://github.com/test-fullautomation/RobotFramework_AIO/actions/runs/5066026691/jobs/9095793247#step:6:398
=> I checked on my OSD machine and found that the extension `.jar` is missing for plantuml configuration on Linux:
current configuration:
```
   "PLANT_UML" : {
                  "WINDOWS" : "%GENDOC_PLANTUML_PATH%/plantuml.jar",
                  "LINUX"   : "${GENDOC_PLANTUML_PATH}/plantuml"
                 }
```
It should be changed to `"LINUX"   : "${GENDOC_PLANTUML_PATH}/plantuml.jar"` 

Thank you,
Ngoan

**Comment by HolQue** [comment]
Hi Ngoan,

`plantuml` without extension was only an assumption I made. ;-)

I derived this assumption from the fact that `pdflatex` and `java` do not have an extension under Linux.

I will take care of the fix.

**Comment by ngoan1608** [comment]
Hi Thomas,

Please refer my idea about your latest comments:

> * build process need to use plantuml of vscodium for genpackagedoc execution.
>   Therefore vscodium has to be aggregated before python (with setup.py of repositories) will be aggregated.
>   After vscodium aggregation build process has to set the GENDOC_PLANTUML_PATH properly.

=> Current build order is already satisfied this requirement. `install` step installs vscode and its extension then `build` step run the `setup.py` for each repo. `GENDOC_PLANTUML_PATH` is set due to the location of installed vscode extension.

> * Installers (Windows, Linux, OSS) need to set GENDOC_PLANTUML_PATH, too. 

=> For sure `GENDOC_PLANTUML_PATH` can be added in the installers. But I see users (testers who using framework) will not use it. We (developers) and who want to contribute to this repo will use it (for development). 

> This is required that after installation SeffTest can be executed. genpackagedoc selftest required plantuml to pass.

In pipeline ([changes](https://github.com/test-fullautomation/RobotFramework_AIO/commit/1042b4eae77c0cadeea2983af29c1fbb3a1c3da4#diff-27e745ce906231078ca53d4b985d91b855d8400961a0da9e7b758adcb3c3539b) in my previous comment) I set `GENDOC_PLANTUML_PATH` accordingly for selftest job and it works fine. Moreover, selftest is not available in the installers (for users).
So, my idea is `GENDOC_PLANTUML_PATH` is not required for the installers and we mentioned about this env var in README for us and contributors (developers). 

It is just my feeling, so please let me know in case this env var is still required for installers. Then I will add new commit for this change.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi Ngoan,
same like with TML I want in future to install the SelfTest, too.
This is a useful additional source how to implement test cases.
So, it's good when the installers install `GENTDOC_PLANTUML_PATH`, too.
Beside of this the envar doesn't take significant memory or space.

Please create a new pull-request with envars installed. I already merged #99

Thank you,
 Thomas

**Comment by ngoan1608** [comment]
The remained issue has been solved within merged PR https://github.com/test-fullautomation/RobotFramework_AIO/pull/102

**Comment by test-fullautomation** [comment]
solved and already merged with https://github.com/test-fullautomation/RobotFramework_AIO/pull/102
